/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import Login.login;
import controler.DocGia_Controller;
import controler.Sach_Controller;
import controler.MuonTra_Controller;
import controler.NhapSach_Controller;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import model.Model_ChiTietSachTra;
import model.Model_DocGia;
import model.Model_Sach;
import notification.Notification;

/**
 *
 * @author Think Pad
 */
public class Form_MuonTra extends javax.swing.JPanel {

    public static List<Model_Sach> arrSach = new ArrayList<>();
    public static List<Model_DocGia> arrDocGia = new ArrayList<>();
    public static List<Model_ChiTietSachTra> arrTinhTrangSach = new ArrayList<>();
    private String madg = "", tendg = "", listmasachmuon = "";
    String[] columnNametdanhsachms = {"Mã Sách", "Tên Sách", "Thể loại", "Tác Giả", "Số Lượng"};
    DefaultTableModel tblDanhSachms = new DefaultTableModel(columnNametdanhsachms, 0);
    String[] columnNametsachmuonms = {"Mã Sách", "Tên Sách", "SL Còn Lại", "SLượng Mượn"};
    DefaultTableModel tblDanhSachMuonms = new DefaultTableModel(columnNametsachmuonms, 0);
    String[] columnNametttsach = {"Số PM", "Mã Sách", "Tên Sách", "Số Lượng", "Tình Trạng", "Hạn Trả"};
    DefaultTableModel tblTinhTrangSachh = new DefaultTableModel(columnNametttsach, 0);
    int slm = 0;
    int slt = 0;

    /**
     * Creates new form Form_TraSach
     */
    public Form_MuonTra() {
        initComponents();
        LayNguonMaSach();
        LayNguonSach("Sách");
        bttrasach.setEnabled(false);
    }

    public void LayNguonMaSach() {

        try {
            arrSach = MuonTra_Controller.LayNguonSach("Sách");
        } catch (SQLException ex) {
            Logger.getLogger(Form_Sach.class.getName()).log(Level.SEVERE, null, ex);
        }
        cbbmasach.removeAllItems();
        cbbmasach.addItem("Sách");
        for (int i = 0; i < arrSach.size(); i++) {

            cbbmasach.addItem(arrSach.get(i).getMaSach());
        }
    }

    public void LayNguonSach(String masach) {
        try {
            arrSach = MuonTra_Controller.LayNguonSach(masach);
        } catch (SQLException ex) {
            Logger.getLogger(Form_Sach.class.getName()).log(Level.SEVERE, null, ex);
        }
        tblDanhSachms.setRowCount(0);
        tbSach.setModel(tblDanhSachms);
        arrSach.forEach(p
                -> {
            tblDanhSachms.addRow(new Object[]{
                p.getMaSach(), p.getTenSach(), p.getTenTL(), p.getTacGia(), p.getSoLuong()
            });
        }
        );
    }

    public void LayNguonTinhTrangSach(String madg) {
        try {
            arrTinhTrangSach = MuonTra_Controller.LayNguonTinhTrangSach(madg);
        } catch (SQLException ex) {
            Logger.getLogger(Form_Sach.class.getName()).log(Level.SEVERE, null, ex);
        }
        tblTinhTrangSachh.setRowCount(0);
        tbtinhtrangsach.setModel(tblTinhTrangSachh);
        arrTinhTrangSach.forEach(p
                -> {
            tblTinhTrangSachh.addRow(new Object[]{
                p.getSoPM(), p.getMaSach(), p.getTenSach(), p.getSoLuong(), p.getTinhTrang(), p.getHanTra()
            });
        }
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        table1 = new swing.Table();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txtmadgms = new javax.swing.JTextField();
        btktmadgms = new swing.button();
        jLabel4 = new javax.swing.JLabel();
        txttendgms = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtsosachmuonms = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtsoquahanms = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btresetms = new swing.button();
        jPanel5 = new javax.swing.JPanel();
        button5 = new swing.button();
        button6 = new swing.button();
        jLabel2 = new javax.swing.JLabel();
        cbbmasach = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbsachmuon = new swing.Table();
        button7 = new swing.button();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbSach = new swing.Table();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        txtmadgts = new javax.swing.JTextField();
        bttrasach = new swing.button();
        jLabel7 = new javax.swing.JLabel();
        txtmasachts = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btkiemtramadgts = new swing.button();
        txtsoluongmts = new javax.swing.JTextField();
        txtsoluongtrats = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txttensachts = new javax.swing.JTextField();
        txttendgts = new javax.swing.JTextField();
        btresetts = new swing.button();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbtinhtrangsach = new swing.Table();

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Sách", "Tên Sách", "Thể Lọa", "Tác Giả", "Số Lượng"
            }
        ));
        jScrollPane3.setViewportView(table1);

        setPreferredSize(new java.awt.Dimension(1140, 795));

        jTabbedPane1.setBackground(new java.awt.Color(255, 102, 102));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1140, 795));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 3));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));

        txtmadgms.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        btktmadgms.setText("Kiểm tra");
        btktmadgms.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btktmadgms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btktmadgmsActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Tên Độc giả");

        txttendgms.setEditable(false);
        txttendgms.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Số lượng sách đang mượn:");

        txtsosachmuonms.setEditable(false);
        txtsosachmuonms.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtsosachmuonms.setText("0");
        txtsosachmuonms.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Số lượng sách quá hạn:");

        txtsoquahanms.setEditable(false);
        txtsoquahanms.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtsoquahanms.setText("0");
        txtsoquahanms.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Mã Độc Giả");

        btresetms.setText("Reset");
        btresetms.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btresetms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btresetmsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txttendgms)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtmadgms, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btktmadgms, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btresetms, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtsosachmuonms, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                    .addComponent(txtsoquahanms))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmadgms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btktmadgms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txttendgms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtsosachmuonms)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtsoquahanms)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(btresetms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 3));

        button5.setText("Kiểm tra");
        button5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });

        button6.setText("Thêm");
        button6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        button6.setStyle(swing.button.ButtonStyle.DESTRUCTIVE);
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Mã Sách");

        cbbmasach.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cbbmasach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbmasachActionPerformed(evt);
            }
        });

        tbsachmuon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Sách", "Tên Sách", "SL Còn Lại", "SLượng Mượn"
            }
        ));
        jScrollPane5.setViewportView(tbsachmuon);

        button7.setText("Mượn Sách");
        button7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cbbmasach, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbbmasach, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        tbSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(tbSach);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mượn Sách", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMaximumSize(new java.awt.Dimension(1232, 906));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 3));

        txtmadgts.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        bttrasach.setText("Trả Sách");
        bttrasach.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bttrasach.setStyle(swing.button.ButtonStyle.DESTRUCTIVE);
        bttrasach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttrasachActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Mã Sách");

        txtmasachts.setEditable(false);
        txtmasachts.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Mã Độc Giả");

        btkiemtramadgts.setText("Kiểm tra");
        btkiemtramadgts.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btkiemtramadgts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btkiemtramadgtsActionPerformed(evt);
            }
        });

        txtsoluongmts.setEditable(false);
        txtsoluongmts.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtsoluongtrats.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Số Lượng Trả");

        txttensachts.setEditable(false);
        txttensachts.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txttendgts.setEditable(false);
        txttendgts.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btresetts.setText("Reset");
        btresetts.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btresetts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btresettsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bttrasach, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btresetts, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btkiemtramadgts, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmadgts)
                            .addComponent(txttendgts)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(txtsoluongmts, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtsoluongtrats, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txttensachts, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txtmasachts, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtmadgts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(txttendgts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btkiemtramadgts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtmasachts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txttensachts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtsoluongtrats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsoluongmts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(bttrasach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btresetts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 3));

        tbtinhtrangsach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Số PM", "Mã Sách", "Tên Sách", "Số Lượng", "Tình Trạng", "Hạn Trả"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbtinhtrangsach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbtinhtrangsachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbtinhtrangsach);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 896, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 197, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Trả Sách", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbbmasachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbmasachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbmasachActionPerformed

    private void btktmadgmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btktmadgmsActionPerformed
        if (txtmadgms.getText().length() <= 0) {
            Notification panel = new Notification((JFrame) SwingUtilities.getWindowAncestor(this), Notification.Type.WARNING, Notification.Location.BOTTOM_RIGHT, "Bạn chưa nhập mã độc giả");
            panel.showNotification();
            txtmadgms.requestFocus();
            return;
        }
        try {
            arrDocGia = DocGia_Controller.LayNguonDG(txtmadgms.getText());
            if (arrDocGia.size() == 0) {
                Notification panel = new Notification((JFrame) SwingUtilities.getWindowAncestor(this), Notification.Type.WARNING, Notification.Location.BOTTOM_RIGHT, "Không tìm thấy độc giả");
                panel.showNotification();
                txtmadgms.requestFocus();
            } else {
                for (Model_DocGia dg : arrDocGia) {
                    madg = dg.getMaDG();
                    tendg = dg.getTenDG();
                    txttendgms.setText(tendg);
                }
                txtsosachmuonms.setText("" + MuonTra_Controller.getslSachMuon(madg));
                txtsoquahanms.setText("" + MuonTra_Controller.getslSachMuonQuaHan(madg));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Form_MuonTra.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btktmadgmsActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        LayNguonSach(cbbmasach.getSelectedItem().toString());
    }//GEN-LAST:event_button5ActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        int rowcount = tbsachmuon.getRowCount();
        if (rowcount == 0) {
            Notification panel = new Notification((JFrame) SwingUtilities.getWindowAncestor(this), Notification.Type.WARNING, Notification.Location.TOP_CENTER, "Chưa chọn sách!!");
            panel.showNotification();
            return;
        }
        for (int row = 0; row < rowcount; row++) {
            if (tbsachmuon.getValueAt(row, 2).toString().equals("0")) {
                Notification panel = new Notification((JFrame) SwingUtilities.getWindowAncestor(this), Notification.Type.WARNING, Notification.Location.TOP_CENTER, "Nhập thiếu số lượng sách " + tbsachmuon.getValueAt(row, 1).toString());
                panel.showNotification();
                return;
            }
//            int slt = Integer.valueOf(txtsoluongtrats.getText());
//            int slm = Integer.valueOf(txtsoluongmts.getText());
            if (Integer.valueOf(tbsachmuon.getValueAt(row, 2).toString()) < Integer.valueOf(tbsachmuon.getValueAt(row, 3).toString())) {
                Notification panel = new Notification((JFrame) SwingUtilities.getWindowAncestor(this), Notification.Type.WARNING, Notification.Location.TOP_CENTER, "Số lượng sách không đủ: mã sách " + tbsachmuon.getValueAt(row, 1).toString());
                panel.showNotification();
                return;
            }
        }
        if (txttendgms.getText().equals("")) {
            Notification panel = new Notification((JFrame) SwingUtilities.getWindowAncestor(this), Notification.Type.WARNING, Notification.Location.TOP_CENTER, "Chưa chọn độc giả!!");
            panel.showNotification();
            return;
        }
        String sopm = "";
        try {
            sopm += MuonTra_Controller.autosophieumuon();
            String sql = "insert into chitietmuontra values";
            for (int row = 0; row < rowcount; row++) {
                if (row < rowcount - 1) {
                    sql += "('" + sopm + "', '" + tbsachmuon.getValueAt(row, 0).toString() + "', '" + tbsachmuon.getValueAt(row, 3).toString() + "', 0, null),";
                } else {
                    sql += "('" + sopm + "', '" + tbsachmuon.getValueAt(row, 0).toString() + "', '" + tbsachmuon.getValueAt(row, 3).toString() + "', 0, null)";
                }
            }
            Date currentDate = new Date();
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String ngay = dateFormat.format(currentDate);
            Calendar calendar = Calendar.getInstance();
            calendar.setTime(currentDate);
            calendar.add(Calendar.DAY_OF_MONTH, 15);
            Date newDate = calendar.getTime();
            String ngay15 = dateFormat.format(newDate);
            MuonTra_Controller.ThemMoiPhieuMuon(sopm, txtmadgms.getText(), login.manv, ngay, ngay15);
            MuonTra_Controller.ThemMoiChiTietNhapSach(sql);
            Notification panel = new Notification((JFrame) SwingUtilities.getWindowAncestor(this), Notification.Type.WARNING, Notification.Location.TOP_CENTER, txttendgms.getText() + " đã mượn sách thành công");
            panel.showNotification();
            try {
                arrDocGia = DocGia_Controller.LayNguonDG(txtmadgms.getText());
                if (arrDocGia.size() == 0) {
                    panel = new Notification((JFrame) SwingUtilities.getWindowAncestor(this), Notification.Type.WARNING, Notification.Location.BOTTOM_RIGHT, "Không tìm thấy độc giả");
                    panel.showNotification();
                    txtmadgms.requestFocus();
                } else {
                    for (Model_DocGia dg : arrDocGia) {
                        madg = dg.getMaDG();
                        tendg = dg.getTenDG();
                        txttendgms.setText(tendg);
                    }
                    txtsosachmuonms.setText("" + MuonTra_Controller.getslSachMuon(madg));
                    txtsoquahanms.setText("" + MuonTra_Controller.getslSachMuonQuaHan(madg));
                }
            } catch (SQLException ex) {
                Logger.getLogger(Form_MuonTra.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Form_Sach.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_button7ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        String cbbmas = cbbmasach.getSelectedItem().toString();
        if (!cbbmas.equals(tbSach.getValueAt(0, 0).toString())) {
            LayNguonSach(cbbmasach.getSelectedItem().toString());
        }
        tbsachmuon.setModel(tblDanhSachMuonms);
        int row = tbsachmuon.getRowCount();
        if (!cbbmas.equals("Sách") && !listmasachmuon.contains(cbbmas)) {
            listmasachmuon += cbbmas;
            tblDanhSachMuonms.addRow(new Object[]{
                cbbmas, tbSach.getValueAt(0, 1).toString(), tbSach.getValueAt(0, 4).toString(), 0
            });
        }
    }//GEN-LAST:event_button6ActionPerformed

    private void btresetmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btresetmsActionPerformed
        txtmadgms.setText("");
        txttendgms.setText("");
        txtsoquahanms.setText("0");
        txtsosachmuonms.setText("0");
        cbbmasach.setSelectedIndex(0);
        tblDanhSachMuonms.setRowCount(0);
        LayNguonSach("Sách");

    }//GEN-LAST:event_btresetmsActionPerformed

    private void btresettsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btresettsActionPerformed
        txtmasachts.setText("");
        txttensachts.setText("");
        txtsoluongmts.setText("");
        txtsoluongtrats.setText("");
        bttrasach.setEnabled(false);
        txtmadgts.setText("");
        txttendgts.setText("");
        LayNguonTinhTrangSach("");
    }//GEN-LAST:event_btresettsActionPerformed

    private void btkiemtramadgtsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btkiemtramadgtsActionPerformed
        if (txtmadgts.getText().length() <= 0) {
            Notification panel = new Notification((JFrame) SwingUtilities.getWindowAncestor(this), Notification.Type.WARNING, Notification.Location.BOTTOM_RIGHT, "Bạn chưa nhập mã độc giả");
            panel.showNotification();
            tblTinhTrangSachh.setRowCount(0);
            tbtinhtrangsach.setModel(tblTinhTrangSachh);
            txttendgts.setText("");
            txtmadgts.requestFocus();
            return;
        }
        try {
            arrDocGia = DocGia_Controller.LayNguonDG(txtmadgts.getText());
            if (arrDocGia.size() == 0) {
                Notification panel = new Notification((JFrame) SwingUtilities.getWindowAncestor(this), Notification.Type.WARNING, Notification.Location.BOTTOM_RIGHT, "Không tìm thấy độc giả");
                panel.showNotification();
                tblTinhTrangSachh.setRowCount(0);
                tbtinhtrangsach.setModel(tblTinhTrangSachh);
                txttendgts.setText("");
                txtmadgts.requestFocus();
            } else {
                for (Model_DocGia dg : arrDocGia) {
                    madg = dg.getMaDG();
                    tendg = dg.getTenDG();
                    txttendgts.setText(tendg);
                }
                LayNguonTinhTrangSach(madg);

            }
        } catch (SQLException ex) {
            Logger.getLogger(Form_MuonTra.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btkiemtramadgtsActionPerformed

    private void tbtinhtrangsachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbtinhtrangsachMouseClicked
        int index = tbtinhtrangsach.getSelectedRow();
        if (tbtinhtrangsach.getValueAt(index, 4).equals("0")) {
            txtmasachts.setText(tbtinhtrangsach.getValueAt(index, 1).toString());
            txttensachts.setText(tbtinhtrangsach.getValueAt(index, 2).toString());
            txtsoluongmts.setText(tbtinhtrangsach.getValueAt(index, 3).toString());
            txtsoluongtrats.setText("");
            bttrasach.setEnabled(true);
        } else {
            txtmasachts.setText("");
            txttensachts.setText("");
            txtsoluongmts.setText("");
            txtsoluongtrats.setText("");
            bttrasach.setEnabled(false);
        }
    }//GEN-LAST:event_tbtinhtrangsachMouseClicked

    private void bttrasachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttrasachActionPerformed
        if (txtsoluongtrats.getText().equals("")) {
            Notification panel = new Notification((JFrame) SwingUtilities.getWindowAncestor(this), Notification.Type.WARNING, Notification.Location.TOP_CENTER, "Chưa nhập số lượng sách trả!");
            panel.showNotification();
            return;
        }

        try {
            int slt = Integer.valueOf(txtsoluongtrats.getText());
            int slm = Integer.valueOf(txtsoluongmts.getText());
            System.out.println(slt);
            if (slt > slm || slt < 0) {
                Notification panel = new Notification((JFrame) SwingUtilities.getWindowAncestor(this), Notification.Type.WARNING, Notification.Location.TOP_CENTER, "Yêu cầu sô lượng trả phải nhỏ hơn hoặc bằng số lượng sách mượn > 0!");
                panel.showNotification();
                return;
            } else {
                Date currentDate = new Date();
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                String ngay = dateFormat.format(currentDate);
                String tinhtrang = "";
                if (slt == slm) {
                    tinhtrang += "1";
                } else {
                    tinhtrang += "1" + slt;
                }
                int index = tbtinhtrangsach.getSelectedRow();
                MuonTra_Controller.UpdateChiTietMuonTra(tbtinhtrangsach.getValueAt(index, 0).toString(), txtmasachts.getText(), tinhtrang, slt, ngay);
                LayNguonTinhTrangSach(madg);
                txtmasachts.setText("");
                txttensachts.setText("");
                txtsoluongmts.setText("");
                txtsoluongtrats.setText("");
            }
        } catch (NumberFormatException ex) {
            Notification panel = new Notification((JFrame) SwingUtilities.getWindowAncestor(this), Notification.Type.WARNING, Notification.Location.TOP_CENTER, "Yêu cầu sô lượng phải là kiểu số nguyên!");
            panel.showNotification();
            return;
        }
    }//GEN-LAST:event_bttrasachActionPerformed

    private void KiemTraMaDg(String madg) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.button btkiemtramadgts;
    private swing.button btktmadgms;
    private swing.button btresetms;
    private swing.button btresetts;
    private swing.button bttrasach;
    private swing.button button5;
    private swing.button button6;
    private swing.button button7;
    private javax.swing.JComboBox<String> cbbmasach;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private swing.Table table1;
    private swing.Table tbSach;
    private swing.Table tbsachmuon;
    private swing.Table tbtinhtrangsach;
    private javax.swing.JTextField txtmadgms;
    private javax.swing.JTextField txtmadgts;
    private javax.swing.JTextField txtmasachts;
    private javax.swing.JTextField txtsoluongmts;
    private javax.swing.JTextField txtsoluongtrats;
    private javax.swing.JTextField txtsoquahanms;
    private javax.swing.JTextField txtsosachmuonms;
    private javax.swing.JTextField txttendgms;
    private javax.swing.JTextField txttendgts;
    private javax.swing.JTextField txttensachts;
    // End of variables declaration//GEN-END:variables
}
